name: Deploy app to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
      - run: dotnet publish AutoCut.Frontend/AutoCut.Frontend.csproj -c Release -o release --nologo -p GHPages=true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot
  deploy:
    needs: publish
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
