name: Deploy app to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to master
        uses: actions/checkout@v3.3.0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
      - name: Publish project
        run: dotnet publish AutoCut.Frontend/AutoCut.Frontend.csproj -c Release -o release --nologo -p GHPages=true
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: release/wwwroot
          
  deploy:
    needs: publish

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 
